### ISSUE TITLE
Test dataset rquired for testing metric availability of license

### ISSUE THREAD

**Issue by G0URAB** [projekt-opal/test-cases#1]
For new test-datasets, please answer 3 questions:  

**1. In which ttl-file is the dataset?** [note 1] and [note 2]  
https://hobbitdata.informatik.uni-leipzig.de/OPAL/OpalGraph/2019-06-24/
model1.ttl

**2. What is the realted dataset-URI?** [note 3]  
<http://projekt-opal.de/dataset/_mcloudde_stadtmoersbersichtskartederinnenstadtvonmoers>

**3. Why is the dataset required? What is not contained in the available datasets?**
The requested dataset has distributions with licenses. In the available dataset, distribution has no licenses.

* [note 1] For the test-set opal-2019-06-24, the possible datasets are available here: https://hobbitdata.informatik.uni-leipzig.de/OPAL/OpalGraph/2019-06-24/
* [note 2] e.g. model50.ttl
* [note 3] e.g. http://projekt-opal.de/dataset/https___europeandataportal_eu_set_data__3dff988d_59d2_415d_b2da_818e8ef31117_

**Comment by adibaba** [comment]
added the test set
